-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 11:15:08 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Клиенты`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Клиенты` (
  `id_клиенты` INT NOT NULL AUTO_INCREMENT,
  `Название` VARCHAR(100) NOT NULL,
  `Телефон` VARCHAR(20) NULL,
  `Контактное_лицо` VARCHAR(100) NULL,
  `адрес` VARCHAR(200) NULL,
  `инн` VARCHAR(12) NULL,
  PRIMARY KEY (`id_клиенты`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Кампании`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Кампании` (
  `id_кампании` INT NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(100) NOT NULL,
  `дата_старта` DATE NULL,
  `дата_окончания` DATE NULL,
  `id_клиента` INT NULL,
  PRIMARY KEY (`id_кампании`),
  INDEX `fk_кампании_клиенты_idx` (`id_клиента` ASC) VISIBLE,
  CONSTRAINT `fk_кампании_клиенты`
    FOREIGN KEY (`id_клиента`)
    REFERENCES `mydb`.`Клиенты` (`id_клиенты`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Площадки`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Площадки` (
  `idПлощадки` INT NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(100) NOT NULL,
  `тип` VARCHAR(50) NULL,
  `стоимость_за_единицу` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idПлощадки`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Размещения`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Размещения` (
  `id_кампании` INT NOT NULL,
  `id_площадки` INT NOT NULL,
  `стоимость` DECIMAL(12,2) NULL,
  PRIMARY KEY (`id_кампании`, `id_площадки`),
  INDEX `fk_размещения_площадки_idx` (`id_площадки` ASC) VISIBLE,
  CONSTRAINT `fk_размещения_кампании`
    FOREIGN KEY (`id_кампании`)
    REFERENCES `mydb`.`Кампании` (`id_кампании`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_размещения_площадки`
    FOREIGN KEY (`id_площадки`)
    REFERENCES `mydb`.`Площадки` (`idПлощадки`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`сотрудники`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`сотрудники` (
  `idсотрудники` INT NOT NULL AUTO_INCREMENT,
  `фамилия` VARCHAR(50) NOT NULL,
  `имя` VARCHAR(50) NOT NULL,
  `отчество` VARCHAR(50) NULL,
  `должность` VARCHAR(100) NULL,
  `процент_от_сделки` DECIMAL(5,2) NULL,
  PRIMARY KEY (`idсотрудники`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Задачи_на_кампанию`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Задачи_на_кампанию` (
  `id_задачи` INT NOT NULL AUTO_INCREMENT,
  `id_сотрудники` INT NOT NULL,
  `id_кампании` INT NOT NULL,
  `задача` VARCHAR(200) NOT NULL,
  `срок` DATE NULL,
  `статус` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_задачи`),
  INDEX `fk_задачи_сотрудники_idx` (`id_сотрудники` ASC) VISIBLE,
  INDEX `fk_задачи_кампании_idx` (`id_кампании` ASC) VISIBLE,
  CONSTRAINT `fk_задачи_сотрудники`
    FOREIGN KEY (`id_сотрудники`)
    REFERENCES `mydb`.`сотрудники` (`idсотрудники`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_задачи_кампании`
    FOREIGN KEY (`id_кампании`)
    REFERENCES `mydb`.`Кампании` (`id_кампании`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;